### ISSUE TITLE
Rename FeaturesContainer to Classifier

### ISSUE THREAD

**Issue by enikao** [LIonWeb-org/organization#105]
Name is weird, because it describes the function of the element. Other M3 elements have names to describe their nature.

**Comment by joswarmer** [comment]
Done on Juli 7 2023

**Comment by enikao** [comment]
On 2023-07-07, we decided to rename `FeaturesContainer` to `Classifier`.

Rationale: Name is weird, because it describes the function of the element. Other M3 elements have names to describe their nature.

`Classifier` is not ideal either, as the symmetric specialization of this would be `Class` rather than `Concept`. However, "classification" is a term in its own, and aptly fits this entity.
We discussed variants of `Type` (e.g. `ObjectType`) for name, symmetric to `DataType`. If we used `Type` instead of `LanguageEntity` (#147), there would be a nice symmetry. However, _type_ is very easy to mix up with typesystem concerns, which is often very confusing.
