### ISSUE TITLE
Use Cases for Repo Access API

### ISSUE THREAD

**Issue by markusvoelter** [LIonWeb-org/organization#3]
Please provide initial input in this document (should be shared with all of us): https://docs.google.com/document/d/1UDlqyB1JIsX0oc-zfLOQgyNU-iOYC7-qYHocv7rEKSs/edit

**Comment by enikao** [comment]
Use cases are now at https://github.com/LIonWeb-org/organization/blob/main/documentation/use-cases.adoc
