### ISSUE TITLE
Migrate diagrams from PlantUML to Mermaid

### ISSUE THREAD

**Issue by dslmeinte** [LIonWeb-org/organization#66]
We're currently putting PlantUML diagrams (`.puml` files) in the documentation, alongside a rendering to SVG (`.svg` files). However, this has the disadvantage that generation of the SVG file is not automatic, but requires either a manual action in an IDE plugin, or executing a JAR. Not terribly difficult, still a hindrance...

GitHub renders [Mermaid](https://mermaid.js.org/#/) diagrams on the web site, without the need for a GitHub Action or additional stuff. The syntax is quite close to PlantUML (as one'd expect), so migration shouldn't be too hard (and e.g. already done in the TS repo).

**Comment by enikao** [comment]
We now generate AsciiDoctor with full PlantUML support (e.g. https://lionweb-org.github.io/organization/lioncore/metametamodel.html#_overview ). Thus, GitHub rendering compatibility is not that important any more.
