### ISSUE TITLE
Introducing the builtin interface INamed

### ISSUE THREAD

**Issue by ftomassetti** [LIonWeb-org/organization#86]
If we introduce this interface we could use in serialization, by populating `resolveInfo` based on the value of the `name` property of `Named`

**Comment by enikao** [comment]
In the meeting on 2023-06-09, we decided to have this interface, and have M3 `NamespacedEntity` / `Language` elements implement the new interface. We'll see during implementation whether this reference from M3 to stdlib creates issues.

**Comment by enikao** [comment]
Decision via [Slack](https://lionweb.slack.com/archives/C05737CGZDE/p1687857267787459): call the interface `INamed`.

**Comment by enikao** [comment]
For reference: The agreed ids and keys are listed in [metamodel docs](https://lionweb-org.github.io/organization/lioncore/metametamodel/metametamodel.html)
