### ISSUE TITLE
In-process API for processors

### ISSUE THREAD

**Issue by sergej-koscejev** [LIonWeb-org/organization#95]
- To integrate with other systems LIonWeb defines a notification API, describing deltas and notifications to be sent.
    - For example, in order to make our models searchable we want to update an ElasticSearch/OpenSearch index as the model changes.
    - MV: what is the difference between deltas and notifications?
- If the information in notifications is not sufficient, the downstream system needs to request more information to perform its task.
    - MV: "information" is very generic. You mean nodes, right?
    - For example, change notifications are sent per each individual node but the search service tracks "documents" that correspond to root nodes and their subtrees. This means that we at the very least need to know the containing root of the node that was changed.
- This can be somewhat mitigated by caching
    - For example, keeping a containing root in cache in case it is needed by future requests, and invalidating/updating it on notifications.
    - MV: cache where?
- This integration scenario can be seen as a very simple model analysis.
- More complex analyses (such as type inference, model checking, or data flow analysis) require complex model navigation, with navigation paths often dependent on the concepts of nodes (polymorphic). Naively performing an HTTP request for each operation would make the analysis too slow.
- This problem can be somewhat mitigated by batching
    - For example, when resolving a reference, immediately ask for the containing root of the reference target, or perhaps even the entire model.
- Requesting additional information about nodes, with or without batching and caching, can be seen as maintaining a (partial) replica of the original repository and then performing an analysis on it locally (in the same process).
- An in-process analysis could also run in the original repository directly, only sending to the client the ready results of the analysis (and their updates) or writing it directly back into the repository as a derived model.
- This problem also comes up in the world of relational databases and is solved in two ways:
    - by defining a standard query language (SQL) to fetch the necessary data to the client which would perform its own analysis locally,
    - by supporting stored procedures which run in-process on the server.
- We argue that it would make sense for LIonWeb to explore defining such a standard query language or a standard API for "stored procedures"/local analyses or explore the notion of in-process processors.

**Comment by enikao** [comment]
Documented in reference architecture (https://github.com/LIonWeb-org/.github/tree/main/profile), we see model API as in scope of LIonWeb, but _secondary_ priority.
